### ISSUE TITLE
Fatal error: Uncaught exception 'StGeorgeIPG\Exceptions\TransactionFailedException' with message 'Transaction failed after 0 tries.' 

### ISSUE THREAD

**Issue by hayden-t** [mitchdav/st-george-ipg#3]
Hi again, i just installed this and tried running with a test transaction but the error is not very clear what is going wrong:

> Fatal error: Uncaught exception 'StGeorgeIPG\Exceptions\TransactionFailedException' with message 'Transaction failed after 0 tries.' in /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Client.php:314 Stack trace: #0 /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Client.php(312): StGeorgeIPG\Client->getResponse(Object(StGeorgeIPG\Request), 0) #1 /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Client.php(312): StGeorgeIPG\Client->getResponse(Object(StGeorgeIPG\Request), 1) #2 /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Client.php(312): StGeorgeIPG\Client->getResponse(Object(StGeorgeIPG\Request), 2) #3 /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Client.php(347): StGeorgeIPG\Client->getResponse(Object(StGeorgeIPG\Request), 3) #4 /home/user/public_html/_webpay/_new/test.php(32): StGeorgeIPG\Client->execute(Object(StGeorgeIPG\Request)) #5 {main} thrown in /home/user/public_html/_composer_libs/vendor/mitchdav/st-george-ipg/src/Client.php on line 314

this is my code:

```
<?php


require __DIR__ . '/../../_composer_libs/vendor/autoload.php';

use StGeorgeIPG\Client;
use StGeorgeIPG\Providers\WebService;

$clientId            = getenv('ourclientnumber');
$authenticationToken = getenv('ourauthtoken');

$webService = new WebService();

$webService->setClientId($clientId)
           ->setAuthenticationToken($authenticationToken);

$client = new Client($webService);

use StGeorgeIPG\Exceptions\ResponseCodes\Exception;


$amount     = 1.00; // In dollars
$cardNumber = 'myrealccnumber';
$month      = 1;
$year       = 2021;

$purchaseRequest = $client->purchase($amount, $cardNumber, $month, $year);

try {
    $purchaseResponse = $client->execute($purchaseRequest);

    echo 'The charge was successful.' . "\n";
} catch (Exception $ex) {
    echo 'The charge was unsuccessful.' . "\n";
    echo $ex->getMessage() . "\n";

    var_dump($purchaseRequest);
    var_dump($ex->getResponse());
}


?>
```

**Comment by hayden-t** [comment]
being tired my problem was this: 
$clientId            = getenv('ourclientnumber');
$authenticationToken = getenv('ourauthtoken');
needs to be
$clientId            = 'ourclientnumber';
$authenticationToken = 'ourauthtoken';
